import uuid
import pandas as pd

df = pd.read_csv("../Data/set/postings_sample.csv")

# For small data it's fine to use this approach to populate ( reason I am doing this is to turn this project into one of my db course assignment )
# SQL table for large scale dummy file we need to directly load
# According to my common sense I might be wrong!
# Nobody lets me intern how would I know things in large scale?

'''
We have normalized table so let's break down the data into subframe.

'''
df_cols = df.columns.tolist()

normalised_cols = ['Weight_SkillMatch', 'Weight_SkillDepth', 'Weight_Experience', 'Weight_Education', 'Weight_Certifications', 'Weight_ActiveContribs']

# In our posting we need to eliminate this one column called case
posting_cols = [i for i in df_cols if i not in normalised_cols and i != "Case"]
df_posting = df[posting_cols]
df_weights = df[normalised_cols]

''' Posting has one-to-one reference, UUID are auto-generated by
 SQL or powerful asp.net's ORM no idea but for foreign key reference we
 will generate here in python and SQL cols are created in different conventions. '''




