import os
import uuid
import psycopg2
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

df = pd.read_csv("../Data/set/postings_sample.csv")



# For small data it's fine to use this approach to populate ( reason I am doing this is to turn this project into one of my db course assignment )
# SQL table for large scale dummy file we need to directly load

'''
We have normalized table so let's break down the data into subframe.

'''
df['Weightsid'] = [str(uuid.uuid4()) for _ in range(len(df))] # first create this unique GUID mapping and then separate the table
df_cols = df.columns.tolist()

normalised_cols = ['Weight_SkillMatch', 'Weight_SkillDepth', 'Weight_Experience', 'Weight_Education', 'Weight_Certifications', 'Weight_ActiveContribs']

# In our posting we need to eliminate this one column called case
posting_cols = [i for i in df_cols if i not in normalised_cols and i != "Case" and i != ""]
df_posting = df[posting_cols]
df_weights = df[normalised_cols]
df_weights['Id'] = df_posting['Weightsid'] # add that foreign key reference

''' Posting has one-to-one reference, UUID are auto-generated by
 SQL or powerful asp.net's ORM no idea but for foreign key reference we
 will generate here in python and SQL cols are created in different conventions. '''



posting_path = "./Export/posting.csv"
weights_path = "./Export/weights.csv"

if not os.path.isfile(posting_path) and not os.path.isfile(weights_path):
    df_posting.to_csv("./Export/posting.csv", index=False)
    df_weights.to_csv("./Export/weights.csv", index=False)

posting_load_sql = """
    COPY posting
    FROM STDIN
    WITH (FORMAT CSV, HEADER TRUE);
"""

weights_load_sql = """
    COPY ScoringWeights
    FROM STDIN
    WITH (FORMAT CSV, HEADER TRUE);
"""
''' It's getting little ticky I need to separate tables again  '''
print((df_posting.columns.tolist()))
# connection_string = os.getenv('CONNECTION_STRING')
#
# conn = psycopg2.connect(connection_string)
# cur = conn.cursor()
#
# with open(posting_path, 'r', encoding='utf-8') as f:
#     cur.copy_expert(sql=posting_load_sql, file=f)
#
# with open(weights_path, 'r', encoding='utf-8') as f:
#     cur.copy_expert(sql=weights_load_sql, file=f)
#
# conn.commit()
# cur.close()
# conn.close()
